# Generated by Django 3.2.9 on 2021-11-15 05:26

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='full name')),
                ('unit', models.CharField(choices=[('1-3', '1-3'), ('1-4', '1-4'), ('1-5', '1-5'), ('1-6', '1-6'), ('1-7', '1-7'), ('1-8', '1-8'), ('1-9', '1-9'), ('1-11', '1-11'), ('1LDR', '1st Div Leadership'), ('OTHER', 'Others')], max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='SG')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='full name')),
                ('unit', models.CharField(blank=True, choices=[('1-3', '1-3'), ('1-4', '1-4'), ('1-5', '1-5'), ('1-6', '1-6'), ('1-7', '1-7'), ('1-8', '1-8'), ('1-9', '1-9'), ('1-11', '1-11'), ('1LDR', '1st Div Leadership'), ('OTHER', 'Others')], max_length=5)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='SG')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='Buddy FIT UID')),
                ('nric', models.CharField(blank=True, max_length=4, verbose_name='NRIC (Last 4 characters)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FIT.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=40)),
                ('date_time', models.DateTimeField()),
                ('duration', models.IntegerField(default=60, verbose_name='duration (in mins)')),
                ('call_link', models.URLField(blank=True)),
                ('instructions', models.CharField(blank=True, max_length=50)),
                ('conducting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conducting', to='FIT.facilitator')),
                ('participants', models.ManyToManyField(blank=True, through='FIT.Participation', to='FIT.Participant')),
                ('safety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='safety', to='FIT.facilitator')),
            ],
        ),
        migrations.AddField(
            model_name='participation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FIT.session'),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('session', 'participant')},
        ),
    ]
